# Generated by Django 6.1 on 2026-09-10 18:01
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
