# Generated by Django 6.1.1 on 2026-09-12 15:00

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='comments', to='blog.post'),
        ),
    ]
